### ISSUE TITLE
Task list week 0

### ISSUE THREAD

**Issue by Matt24905** [Matt24905/E7032E-Cat-door-project#1]
- [x] Learn Git
- [x] Project plan and WBS
- [x] Start writing the report (structure, background, etc)
- [x] Division of roles and responsibilities
- [x] Read about ISO 11784 and ISO 11785
- [x] Create a Git repository
- [x] Read about, and take apart, the cat door
- [x] Read about the current antenna
